### ISSUE TITLE
Rehber Appearance

### ISSUE THREAD

**Issue by SmallSimpleSafe** [Okuyun/Rehber#4]
New background for Iqra reader is much better

Finder could use the same color -- pure white is tiring to eyes

**Comment by a0m0rajab** [comment]
We can use the next modes for appearance:

- Dark mode
- Normal mode 
- Custom mode

**Comment by a0m0rajab** [comment]
I have implemented the dark/light mode. 
for custom mode. I just created the function, will have to add the UI later. 

For experimenting you can use those functions: 
`toggleCustomMode()
setCustomMode(bgcolor, color)
`

**Comment by gulcu** [comment]
Unlike the settings items, "_dark mode_" does not persist between sessions as of now. An additional slight inconvenience is that hovered over text also goes dark, making it unreadable. I think this is because themes are not fully implemented yet, but when they are, the surrounding screens (Mushaf, Mucem, entry pages) should all toggle the dark mode simultaneously.

**Comment by a0m0rajab** [comment]
@gulcu Thank you for your comment.
You are right about the persistence, I did not implement it yet.
I have fixed the hover bug and changed the highlight colour to more suitable one for the dark mode.

**Comment by maeyler** [comment]
Dark mode is almost complete in Finder
We need a similar mode in Mushaf
(low priority)

**Comment by a0m0rajab** [comment]
Dark mode in Finder is done, 
I have to check the other modules (Simi and Reader)
